import {
  script,
  googleAnalytics
} from '../src/index';

export default {
  head: {
    preAppends: function(contents) {
      contents.scripts.removeAll();
    }
  },
  body: {
    appends: [
      googleAnalytics('UA-12345-1'),
      script({
        src: 'bundle.js'
      }),
      script({
        contents: "System.import('app/main')"
      })
    ],
    prepends: [
      `<!-- generated by Jack at ${new Date().toISOString()} -->`
    ]
  }
}
